server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/innotree_data_project
    username: liuchaoyang
    password:
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:mybatis/*.xml
---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: production