server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://kaifa.innotree.local:3306/innotree_data_project
    username: liuchaoyang
    password: KL8o2YGT6b9Zj67Q

mybatis:
  mapper-locations: classpath:mybatis/*.xml
---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: production